routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/login/{driver}', 'Auth\LoginController@redirectToProvider')->name('login.social');
Route::get('/login/{driver}/callback', 'Auth\LoginController@handleProviderCallback')->name('login.social.callback');
Route::get('/account-confirm', 'Auth\LoginController@accountConfirm')->name('account.confirm');
Route::post('/account-confirm', 'Auth\LoginController@accountConfirmSuccess')->name('account.confirm.success');
Route::post('/account-do-not-confirm', 'Auth\LoginController@accountConfirmDanger')->name('account.confirm.danger');
Route::get('/verify-email/{email}/{verify_token}', 'Auth\RegisterController@verifyEmail')->name('verify.email');

Route::get('/', 'PagesController@index')->name('home');

Route::get('/about', 'PagesController@about');
Route::get('/contacts', 'PagesController@contacts');
Route::get('/advertising', 'PagesController@advertising');
Route::get('/rules', 'PagesController@rules');
Route::get('/privacy', 'PagesController@privacy');
Route::get('/search', 'SearchController@index')->name('search');

Route::get('/news/{category_slug?}', 'ArticlesController@showNewsCategoryPage')
	->where(['category_slug' => '[a-z-]+'])
	->name('news');
Route::get('/news/{category_slug}/{id}-{article_slug}', 'ArticlesController@showNewsPage')
	->where(['category_slug' => '[a-z-]+', 'id' => '[0-9]+'])
	->name('news.single');

Route::get('/articles/{category_slug?}', 'ArticlesController@showArticleCategoryPage')
	->where(['category_slug' => '[a-z-]+'])
	->name('articles');
Route::get('/articles/{category_slug}/{id}-{article_slug}', 'ArticlesController@showArticlePage')
	->where(['category_slug' => '[a-z-]+', 'id' => '[0-9]+'])
	->name('articles.single');

Route::get('/organizations', 'OrganizationsController@showOrganizationCategoriesPage')->name('organizations.categories');
Route::get('/organizations/{category_slug}', 'OrganizationsController@showOrganizationCategoryPage')
	->where(['category_slug' => '[a-z-]+'])
	->name('organizations.category');
Route::get('/organizations/{category_slug}/{subcategory_slug}', 'OrganizationsController@showOrganizationSubcategoryPage')
	->where(['category_slug' => '[a-z-]+', 'subcategory_slug' => '[a-z-]+'])
	->name('organizations.subcategory');
Route::get('/organizations/{category_slug}/{subcategory_slug}/{organization_id}-{organization_slug}', 'OrganizationsController@showOrganizationPage')
	->where(['category_slug' => '[a-z-]+', 'subcategory_slug' => '[a-z-]+', 'id' => '[0-9]+'])
	->name('organizations.single');
Route::post('/organization/like', 'OrganizationsController@likeOrganization')->name('organization.like');
Route::post('/organization-changes', 'OrganizationsController@addChanges');

Route::get('/tags', 'TagsController@tags')->name('tags');
Route::get('/tags/{tag_slug}', 'TagsController@tag')
	->where(['tag_slug' => '[0-9a-z-]+'])
	->name('tag.single');

Route::post('/poll/{slug}', 'PollsController@pollVote')->name('poll');
Route::get('/polls', 'PollsController@showPollsPage');
Route::get('/polls/{id}-{poll_slug}', 'PollsController@showPollPage')
	->where(['id' => '[0-9]+']);

Route::group(['prefix' => 'comment'], function () {
	Route::post('/add', 'CommentsController@addComment')->name('comment.add');
	Route::post('/remove', 'CommentsController@removeComment')->name('comment.remove');
	Route::post('/like', 'CommentsController@likeComment')->name('comment.like');
});

Route::get('/cdn/{project}-{key}.css', 'CdnController@returnStyle')
  ->where(['project' => '[a-z]+', 'key' => '[0-9a-z]+']);

Route::group(['prefix' => 'banners'], function () {
	Route::post('/close-banner', 'BannersController@closeBanner');
	Route::post('/click-counter', 'BannersController@clickCounter');
});

Route::group(['prefix' => 'adverts'], function () {
	Route::get('/', function () {
		return view('adverts.adverts-categories');
	})->name('adverts.category');
	Route::get('/adverts/{category_slug}/{id}-{article_slug}', 'AdvertsController@showNewsPage')
		->where(['category_slug' => '[a-z-]+', 'id' => '[0-9]+'])
		->name('advert.single');
});

Route::post('contacts', 'PagesController@saveContacts');

Route::group(['prefix' => 'profile'], function () {
	Route::get('/', 'ProfileController@profile')->name('profile');
//	Route::get('/notifications', 'ProfileController@notifications')->name('profile.notifications');
//	Route::get('/profile-edit', 'ProfileController@profileEdit')->name('profile.edit');
//	Route::get('/profile-update', 'ProfileController@profileUpdate')->name('profile.update');
//	Route::get('/change-password-edit', 'ProfileController@changePasswordEdit')->name('profile.change-password-edit');
//	Route::get('/change-password-update', 'ProfileController@changePasswordUpdate')->name('profile.change-password-update');
//	Route::get('/comments', 'ProfileController@comments')->name('profile.comments');
//	Route::get('/adverts', 'ProfileController@adverts')->name('profile.adverts');
//	Route::get('/create-advert', 'ProfileController@createAdvert')->name('profile.create-advert');
//	Route::get('/edit-advert', 'ProfileController@editAdvert')->name('profile.edit-advert');
//	Route::get('/update-advert', 'ProfileController@updateAdvert')->name('profile.update-advert');
//	Route::get('/bookmarks', 'ProfileController@bookmarks')->name('profile.bookmarks');
//	Route::get('/hz-button', 'ProfileController@addNewRecords')->name('profile.');
	Route::get('/organization-changes-list', 'ProfileController@organizationChangesIndex');
	Route::get('/organization-edit/{id}', 'ProfileController@organizationChangesShow');
	Route::post('/organization-save', 'ProfileController@organizationChangesStore');
	Route::patch('/organization-save/{id}', 'ProfileController@organizationChangesUpdate');
	Route::delete('/organization-delete/{id}', 'ProfileController@organizationChangesDestroy');
	Route::get('/organization-list', 'ProfileController@organizationList');
});

//Route::get('test-facebook', 'ApiController@sendLinkToFacebook');

Route::get('sitemap-create', function(){
	Artisan::call('sitemap:create');
	return '{success:created}';
});

//Route::get('twitter-post', function (){
//	Artisan::call('twitter:post');
//});

Route::get('cache-clear', function(){
	Artisan::call('cache:clear');
});

//TODO хай поки буде :)
//Route::get('process-images', function () {
//
//	$organizations = \App\Organization::where('id', '>', 59)->get();
//
//	foreach ($organizations as $organization) {
//		$image = Image::make($organization->getCroppedImage('max'));
//		$image->fit(66, 66);
////		return $image->response('jpg', 95);
//
//		$image->encode('jpg', 95);
//
//		Storage::disk('public')
//			->put('organizations/'.$organization->image.'_brief.jpg', (string)$image);
//	}
//});

//Route::get('/test-imgix', function () {
//	return view('test-imgix');
//});

Route::get('/adverts/single', function () {
	return view('adverts.adverts-single');
});

Route::get('/adverts/form', function () {
	return view('adverts.adverts-form');
});

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Builder;

class Article extends ParentArticle
{
	protected $attributes = ['type' => 'article'];

	protected static function boot()
	{
		parent::boot();

		static::addGlobalScope('article', function (Builder $builder) {
			$builder->where('type', '=', 'article');
		});
	}

	public function category()
	{
		return $this->belongsTo(ArticleCategory::class, 'category_id', 'id');
	}

	public function getUrl()
	{
		if ($this->id) {
			return url('articles/' . $this->category->slug . '/' . $this->id . '-' . $this->slug);
		}

		return null;
	}
}

app/Http/Controllers/ArticlesController.php
<?php

namespace App\Http\Controllers;

use App\Article;
use App\ArticleCategory;
use App\News;
use App\NewsCategory;
use App\Traits\ShortCode;
use Carbon\Carbon;
use Illuminate\Http\Request;

class ArticlesController extends Controller
{
	use ShortCode;

	public function showNewsCategoryPage(Request $request, $categorySlug = null)
	{
		$news = News::query();

		if (isset($categorySlug)) {
			$news = $news->whereHas('category', function ($query) use ($categorySlug) {
				$query->where('slug', '=', $categorySlug);
			});

			$category = NewsCategory::where('slug', '=', $categorySlug)->active()->firstOrFail();
		}

		$newsModel = new News;
		$bestWeek = $newsModel->bestThanWeek();
		$bestMonth = $newsModel->bestThanMonth();

		$onPage = 8;
		$news = $news->with('category');
		$news = $news->active()->published()->newest()->paginate($onPage);
		$onPage = 'Завантажити ще ' . on_next_page($onPage, $news);
		$showMore = $news->lastPage() !== 1;

		if ($request->ajax()) {
			$returnHTML = view('articles.articles-list')->with([
				'articles' => $news,
				'type'     => 'news',
				'socialBannerPosition' => 5
			])->render();

			return response()->json([
				'html'       => $returnHTML,
				'lastPage'   => $news->lastPage(),
				'onNextPage' => $onPage,
			]);
		}

		$data = [
			'categories' => NewsCategory::active()->get(),
			'articles'   => $news,
			'type'       => 'news',
			'showMore'   => $showMore,
			'onNextPage' => $onPage,
			'best_week'  => $bestWeek,
			'best_month' => $bestMonth,
		];

		if (isset($category)) {
			$data['category'] = $category;
		}

		return view('articles.articles-categories')->with($data);
	}

	public function showArticleCategoryPage(Request $request, $categorySlug = null)
	{
		$articles = Article::query();

		if (isset($categorySlug)) {
			$articles = $articles->whereHas('category', function ($query) use ($categorySlug) {
				$query->where('slug', '=', $categorySlug);
			});

			$category = ArticleCategory::where('slug', '=', $categorySlug)->active()->firstOrFail();
		}

		$article = new Article;
		$bestWeek = $article->bestThanWeek();
		$bestMonth = $article->bestThanMonth();

		$onPage = 8;
		$articles = $articles->with('category')->active()->published()->newest()->paginate($onPage);
		$onPage = 'Завантажити ще ' . on_next_page($onPage, $articles);
		$showMore = $articles->lastPage() !== 1;

		if ($request->ajax()) {
			$returnHTML = view('articles.articles-list')->with([
				'articles' => $articles,
				'type'     => 'articles',
				'socialBannerPosition' => 5
			])->render();

			return response()->json([
				'html'       => $returnHTML,
				'lastPage'   => $articles->lastPage(),
				'onNextPage' => $onPage,
			]);
		}

		$data = [
			'categories' => ArticleCategory::active()->get(),
			'articles'   => $articles,
			'type'       => 'articles',
			'showMore'   => $showMore,
			'onNextPage' => $onPage,
			'best_week'  => $bestWeek,
			'best_month' => $bestMonth,
		];

		if (isset($category)) {
			$data['category'] = $category;
		}

		return view('articles.articles-categories')->with($data);
	}

	public function showNewsPage($categorySlug, $articleId, $articleSlug)
	{
		$news = News::whereHas('category', function ($query) use ($categorySlug) {
				$query->where('slug', '=', $categorySlug);
			})
		->where([
			['id', '=', $articleId],
			['slug', '=', $articleSlug]
		])
		->with('comments')->withCount(['comments' => function($query) {
			$query->where('active', true);
		}])
		->firstOrFail();

		$comments = new \App\Comment;
		$news = $comments->getComments($news);

		$recent = News::where('id', '!=', $news->id)
			->with('category')
			->active()
			->published()
			->orderBy('published_at', 'desc')
			->take(6)
			->get();

		$news->body = advertising_in_content($news->body, 'includes.banners.content-advert');

		$news->body = $this->renderShortCodes($news->body);

		return view('articles.articles-single')->with([
			'article' => $news,
			'type'    => 'news',
			'recent'  => $recent,
			'model'   => 'News'
		]);
	}

	public function showArticlePage($categorySlug, $articleId, $articleSlug)
	{
		$article = Article::whereHas('category', function ($query) use ($categorySlug) {
				$query->where('slug', '=', $categorySlug);
			})
		->where([
			['id', '=', $articleId],
			['slug', '=', $articleSlug]
		])->with('comments')->withCount(['comments' => function($query) {
			$query->where('active', true);
		}])->firstOrFail();

		$comments = new \App\Comment;
		$article = $comments->getComments($article);

		$recent = Article::where('id', '!=', $article->id)
			->with('category')
			->active()
			->published()
			->orderBy('published_at', 'desc')
			->take(6)
			->get();

		$article->body = advertising_in_content($article->body, 'includes.banners.content-advert');
		$article->body = $this->renderShortCodes($article->body);

		return view('articles.articles-single')->with([
			'article' => $article,
			'type'    => 'articles',
			'recent'  => $recent,
			'model'   => 'Article'
		]);
	}
}

resources/views/articles/articles-categories.blade.php
@extends('layouts.layouts-main')

@section('meta')
	@if(isset($category))
		@include('includes.meta', [
			'title' => $category->meta_title,
			'meta_description' => $category->meta_description,
			'meta_keywords' => $category->meta_keywords,
			'og_title' => $category->meta_title,
			'og_description' => $category->meta_description,
			'og_image' => $category->getCroppedImage('og', 'jpg', 'og_image') ?? ($type == 'news' ? asset('images/pages/news.jpg') : asset('images/pages/articles.jpg')),
			'og_image_type' => 'og',
			'active' => $category->active
		])
	@else
		@include('includes.meta', [
			'title' => $type == 'news' ? config('metatags.news.title') : config('metatags.articles.title'),
			'meta_description' => $type == 'news' ? config('metatags.news.description') : config('metatags.articles.description'),
			'meta_keywords' => $type == 'news' ? config('metatags.news.keywords') : config('metatags.articles.keywords'),
			'og_title' => $type == 'news' ? config('metatags.news.title') : config('metatags.articles.title'),
			'og_description' => $type == 'news' ? config('metatags.news.description') : config('metatags.articles.description'),
			'og_image' => $type == 'news' ? asset('images/pages/news.jpg') : asset('images/pages/articles.jpg'),
			'og_image_type' => 'og',
			'active' => true
		])
	@endif
@stop

@section('styles')
	<link rel="stylesheet" href="{{ mix('css/common.css') }}">
	<link rel="stylesheet" href="{{ mix('css/articles.css') }}">
	<link rel="stylesheet" href="{{ asset('libs/lightslider/lightslider.css') }}">
@endsection

@section('content')
	<div class="all-news">

		<div class="breadcrumbs">
			@if(isset($category))
				@include('includes.breadcrumbs', ['links' => [
					['link' => route($type), 'title' => ($type == 'articles' ? 'Статті' : 'Новини')]
				], 'current' => $category->title])
			@else
				@include('includes.breadcrumbs', ['current' => $type == 'articles' ? 'Статті' : 'Новини'])
			@endif
		</div>

		@isset($categories)
			<ul class="categories-list m-lr m-b">
				@foreach($categories->sortBy('order_') as $item)
					<li class="categories-list__item">
						<a href="{{ $item->getUrl() }}"
							 class="btn btn-md btn-transparent btn-bordered btn-{{ $item->class }}
							 {{ isset($category) && $category->id == $item->id ? 'active' : '' }}">
							{{ $item->title }}
						</a>
					</li>
				@endforeach
			</ul>
		@endisset

		@if(isset($articles) && $articles->count() > 0)

			@include('includes.banners.top-banner')

			<div class="articles-list m-t">
				@include('articles.articles-list', [
					'articles' => $articles,
					'socialBannerPosition' => 5
				])
			</div>
			@if(isset($showMore) && $showMore)
				<a class="load-more show-more m-lr m-b"
					 data-current-page="2"
					 data-url="{{ url(Request::path()) }}">{{ $onNextPage }}</a>
			@endif
		@else
			@include('includes.alert', [
				'type' => 'info',
				'class' => 'm-lr m-b',
				'messages' => ['Упс... В даній категорії ще немає матеріалів']
			])
		@endif

		<hr class="m-lr m-b">

		@if(isset($best_week) && count($best_week) > 0)
			<div class="slider-section m-full">
				<div class="slider-section__header">
					<h3 class="slider-section__title">Найцікавіше за тиждень</h3>
					<div class="slider-section__controls">
						<div class="slider-section__controls--prev" id="best-week-news-prev">
							<i class="fal fa-angle-left"></i>
						</div>
						<div class="slider-section__controls--next" id="best-week-news-next">
							<i class="fal fa-angle-right"></i>
						</div>
					</div>
				</div>
				<div class="slider-section__content" id="best-week-news">
					@include('articles.articles-list', ['articles' => $best_week])
				</div>
			</div>

			<hr class="m-full">
		@endif

		@include('includes.banners.horizontal-banner1')

		@if(isset($best_month) && count($best_month) > 0)
			<div class="slider-section m-lr m-t">
				<div class="slider-section__header">
					<h3 class="slider-section__title">Найцікавіше за місяць</h3>
					<div class="slider-section__controls">
						<div class="slider-section__controls--prev" id="best-month-news-prev">
							<i class="fal fa-angle-left"></i>
						</div>
						<div class="slider-section__controls--next" id="best-month-news-next">
							<i class="fal fa-angle-right"></i>
						</div>
					</div>
				</div>
				<div class="slider-section__content" id="best-month-news">
					@include('articles.articles-list', ['articles' => $best_month])
				</div>
			</div>
		@endif

	</div>
@stop

@section('scripts')
	<script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@12.0.0/dist/lazyload.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/sticky-sidebar@3.3.1/dist/sticky-sidebar.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/resize-sensor@0.0.6/ResizeSensor.min.js"></script>

	<script src="{{ asset('js/common-slider.js') }}"></script>
	<script src="{{ asset('libs/lightslider/lightslider-blur-fix.min.js') }}"></script>
	<script>
		commonSlider('best-week-news');
		commonSlider('best-month-news');
	</script>
@stop

resources/views/articles/articles-single.blade.php
@extends('layouts.layouts-main')

@section('schema')
	@include('includes.schema.article-schema')
@endsection

@section('meta')
	@include('includes.meta', [
		'title' => $article->meta_title ?? $article->title,
		'meta_description' => $article->meta_description,
		'meta_keywords' => $article->meta_keywords,
		'og_title' => $article->og_title ?? $article->meta_title,
		'og_description' => $article->og_description ?? $article->meta_description,
		'og_image' => $article->getCroppedImage('og', 'jpg', 'og_image') ?? $article->getCroppedImage('max') ?? ($type == 'news' ? asset('images/pages/news.jpg') : asset('images/pages/articles.jpg')),
		'og_image_type' => $article->getCroppedImage('og', 'jpg', 'og_image') ? 'og' : ($article->getCroppedImage('max') ? 'max' : 'og'),
		'active' => $article->isPublished()
	])
@stop

@section('styles')
	<link rel="stylesheet" href="{{ mix('css/common.css') }}">
	<link rel="stylesheet" href="{{ mix('css/articles.css') }}">
	@if($article->poll)
		<link rel="stylesheet" href="{{ mix('css/polls.css') }}">
	@endif
	<link rel="stylesheet" href="{{ mix('css/comments.css') }}">
	<link rel="stylesheet" href="{{ asset('libs/lightslider/lightslider.css') }}">
@endsection

@section('content')
	<div class="breadcrumbs">
		@include('includes.breadcrumbs', ['links' => [
			['link' => route($type), 'title' => $type == 'articles' ? 'Статті' : 'Новини'],
			['link' => url($article->category->getUrl()), 'title' => $article->category->title]
		], 'current' => $article->title])
		@can('Access to Nova')
			<div class="breadcrumbs-controls tooltip-parent">
				<i class="fal fa-ellipsis-h"></i>
				<div class="tooltip tooltip-left tooltip-controls tooltip-blue">
					<a target="_blank" href="{{ url('/adm/resources/'.$type.'/'.$article->id) }}">Переглянути</a>
					<a target="_blank" href="{{ url('/adm/resources/'.$type.'/'.$article->id.'/edit') }}">Редагувати</a>
				</div>
			</div>
		@endcan
	</div>

	<div class="article-single">

		<div class="article-single__header">
			<div class="article-single__author">
				<div class="article-single__author-avatar">
					<img class="b-lazy"
							 data-src="{{ $article->author->getAvatar() }}"
							 alt="{{ $article->author->name }}">
				</div>
				<div class="article-single__author-information">
					<div class="article-single__author-name">{{ $article->author->name }} {{ $article->author->surname }}</div>
					<div class="article-single__author-role">Автор матеріалу</div>
				</div>
			</div>
			<div class="article-single__information">
				<time class="article-single__information-datetime" datetime="{{ $article->published_at->toAtomString() }}">
					<span>{{ $article->published_at->format('H:i') }}</span>
					<span>{{ $article->published_at->format('d.m.y') }}</span>
				</time>
				<div class="article-single__information-labels btn-container">
					<a class="article-single__information-category btn btn-xl btn-bordered btn-{{ $article->category->class }} active"
						 href="{{ $article->category->getUrl() }}">{{ $article->category->title }}</a>

					@if($article->advertising)
						<div class="btn btn-xl btn-blue circle tooltip-parent">
							<i class="fal fa-dollar-sign"></i>
							<div class="tooltip tooltip-left tooltip-blue">Ця стаття <a href="#commercial-article">комерційна</a>. Адміністрація
								сайту публікує статті з такою поміткою на правах
								реклами.
							</div>
						</div>
					@endif
				</div>
			</div>
		</div>

		<div class="article-single__content media-content">

			<h1>{{ $article->title }}</h1>

			@if(isset($article->source_title) && isset($article->source_link))
				<div class="article-single__content-source">Джерело: <a href="{{ $article->source_link }}" target="_blank" rel="nofollow">{{ $article->source_title }}</a></div>
			@endif

			@if($article->excerpt)
				<p>{{ $article->excerpt }}</p>
			@endif

			<figure class="media-content__image m-tb m--lr">
				<div class="media-content__image-container">
					<img src="{{ $article->getCroppedImageOrTransparent('low') }}" alt="{{ $article->image_title ?? $article->title }}">
					<picture>
						<source media="(min-width: 992px)"
										data-srcset="{{ $article->getCroppedImageOrError('max', 'webp') }}"
										type="image/webp">
						<source media="(min-width: 992px)"
										data-srcset="{{ $article->getCroppedImageOrError('max', 'jpg') }}">

						<source media="(min-width: 768px) and (max-width: 991px)"
										data-srcset="{{ $article->getCroppedImageOrError('mobile', 'webp') }}"
										type="image/webp">
						<source media="(min-width: 768px) and (max-width: 991px)"
										data-srcset="{{ $article->getCroppedImageOrError('mobile', 'jpg') }}">

						<source media="(min-width: 560px) and (max-width: 767px)"
										data-srcset="{{ $article->getCroppedImageOrError('max', 'webp') }}"
										type="image/webp">
						<source media="(min-width: 560px) and (max-width: 767px)"
										data-srcset="{{ $article->getCroppedImageOrError('max', 'jpg') }}">

						<source media="(min-width: 450px) and (max-width: 559px)"
										data-srcset="{{ $article->getCroppedImageOrError('mobile', 'webp') }}"
										type="image/webp">
						<source media="(min-width: 450px) and (max-width: 559px)"
										data-srcset="{{ $article->getCroppedImageOrError('mobile', 'jpg') }}">

						<img class="b-lazy"
								 data-src="{{ $article->getCroppedImageOrError('card') }}"
								 alt="{{ $article->image_title ?? $article->title }}">
					</picture>
				</div>
				<figcaption>{{ $article->image_title ?? $article->title }}</figcaption>
			</figure>

			@if($type == 'articles')
				@include('includes.banners.horizontal-banner1')
			@endif
			{!! $article->body !!}

			@if($article->poll)
				@include('includes.poll.poll-list', ['poll' => $article->poll])
			@endif

		</div>

		<div class="article-single__footer m-lr m-b">

			<div class="counters">
				<span><i class="fal fa-eye"></i>{{ $article->views }}</span>
				<span><i class="fal fa-comment"></i>{{ $article->comments_count }}</span>
			</div>

			<div id="fb-root"></div>
			<script async defer src="https://connect.facebook.net/uk_UA/sdk.js#xfbml=1&version=v3.2&appId=249421485733779&autoLogAppEvents=1"></script>

			{{-- button subscribe button --}}
			{{--<div class="fb-like" data-href="https://www.facebook.com/kp.city.official"--}}
				 {{--data-layout="button_count"--}}
				 {{--data-action="like"--}}
				 {{--data-size="small"--}}
				 {{--data-show-faces="true"--}}
				 {{--data-share="false"--}}
				 {{--data-colorscheme="light"--}}
			{{--></div>--}}

			{{-- twitter subscribe button --}}
			{{--<a href="https://twitter.com/kp__city?ref_src=twsrc%5Etfw"--}}
			   {{--class="twitter-follow-button"--}}
			   {{--data-show-count="false">Follow @kp__city</a>--}}
			{{--<script async src="https://platform.twitter.com/widgets.js" charset="utf-8"></script>--}}

			@include('includes.social-buttons', ['class' => 'share', 'url' => url(Request::path())])

		</div>

	</div>

	@if(isset($recent) && count($recent) > 0)
		<div class="slider-section m-lr m-t">
			<div class="slider-section__header">
				<h3 class="slider-section__title">Читайте також</h3>
				<div class="slider-section__controls">
					<div class="slider-section__controls--prev" id="slider-recent-prev">
						<i class="fal fa-angle-left"></i>
					</div>
					<div class="slider-section__controls--next" id="slider-recent-next">
						<i class="fal fa-angle-right"></i>
					</div>
				</div>
			</div>
			<div class="slider-section__content" id="slider-recent">
				@include('articles.articles-list', ['articles' => $recent])
			</div>
		</div>

		<hr class="m-t">
	@endif

	@include('comments.comments-list', [
		'comments' => $article->comments_list,
		'totalComments' => $article->comments_count,
		'maxLikes' => $article->max_likes
	])

@endsection

@section('scripts')
	<script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@12.0.0/dist/lazyload.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/sticky-sidebar@3.3.1/dist/sticky-sidebar.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/resize-sensor@0.0.6/ResizeSensor.min.js"></script>

	<script src="{{ asset('js/common-slider.js') }}"></script>
	<script src="{{ asset('libs/lightslider/lightslider-blur-fix.min.js') }}"></script>
	<script>
		$("#article-slider").lightSlider({
			item: 1,
			slideMargin: 0,
			easing: 'ease',
			speed: 300,
			loop: false,
			enableTouch: 0,
			prevHtml: '<i class="fal fa-angle-left"></i>',
			nextHtml: '<i class="fal fa-angle-right"></i>'
		});

		commonSlider('slider-recent');
	</script>
@stop

@section('counter')
	@include('includes.counter', [
		'model' => $model,
		'column' => 'views',
		'id' => $article->id
	])
@endsection