routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Auth::routes();
Route::get('/login/{driver}', 'Auth\LoginController@redirectToProvider')->name('login.social');
Route::get('/login/{driver}/callback', 'Auth\LoginController@handleProviderCallback')->name('login.social.callback');
Route::get('/account-confirm', 'Auth\LoginController@accountConfirm')->name('account.confirm');
Route::post('/account-confirm', 'Auth\LoginController@accountConfirmSuccess')->name('account.confirm.success');
Route::post('/account-do-not-confirm', 'Auth\LoginController@accountConfirmDanger')->name('account.confirm.danger');
Route::get('/verify-email/{email}/{verify_token}', 'Auth\RegisterController@verifyEmail')->name('verify.email');

Route::get('/', 'PagesController@index')->name('home');

Route::get('/about', 'PagesController@about');
Route::get('/contacts', 'PagesController@contacts');
Route::get('/advertising', 'PagesController@advertising');
Route::get('/rules', 'PagesController@rules');
Route::get('/privacy', 'PagesController@privacy');
Route::get('/search', 'SearchController@index')->name('search');

Route::get('/news/{category_slug?}', 'ArticlesController@showNewsCategoryPage')
	->where(['category_slug' => '[a-z-]+'])
	->name('news');
Route::get('/news/{category_slug}/{id}-{article_slug}', 'ArticlesController@showNewsPage')
	->where(['category_slug' => '[a-z-]+', 'id' => '[0-9]+'])
	->name('news.single');

Route::get('/articles/{category_slug?}', 'ArticlesController@showArticleCategoryPage')
	->where(['category_slug' => '[a-z-]+'])
	->name('articles');
Route::get('/articles/{category_slug}/{id}-{article_slug}', 'ArticlesController@showArticlePage')
	->where(['category_slug' => '[a-z-]+', 'id' => '[0-9]+'])
	->name('articles.single');

Route::get('/organizations', 'OrganizationsController@showOrganizationCategoriesPage')->name('organizations.categories');
Route::get('/organizations/{category_slug}', 'OrganizationsController@showOrganizationCategoryPage')
	->where(['category_slug' => '[a-z-]+'])
	->name('organizations.category');
Route::get('/organizations/{category_slug}/{subcategory_slug}', 'OrganizationsController@showOrganizationSubcategoryPage')
	->where(['category_slug' => '[a-z-]+', 'subcategory_slug' => '[a-z-]+'])
	->name('organizations.subcategory');
Route::get('/organizations/{category_slug}/{subcategory_slug}/{organization_id}-{organization_slug}', 'OrganizationsController@showOrganizationPage')
	->where(['category_slug' => '[a-z-]+', 'subcategory_slug' => '[a-z-]+', 'id' => '[0-9]+'])
	->name('organizations.single');
Route::post('/organization/like', 'OrganizationsController@likeOrganization')->name('organization.like');
Route::post('/organization-changes', 'OrganizationsController@addChanges');

Route::get('/tags', 'TagsController@tags')->name('tags');
Route::get('/tags/{tag_slug}', 'TagsController@tag')
	->where(['tag_slug' => '[0-9a-z-]+'])
	->name('tag.single');

Route::post('/poll/{slug}', 'PollsController@pollVote')->name('poll');
Route::get('/polls', 'PollsController@showPollsPage');
Route::get('/polls/{id}-{poll_slug}', 'PollsController@showPollPage')
	->where(['id' => '[0-9]+']);

Route::group(['prefix' => 'comment'], function () {
	Route::post('/add', 'CommentsController@addComment')->name('comment.add');
	Route::post('/remove', 'CommentsController@removeComment')->name('comment.remove');
	Route::post('/like', 'CommentsController@likeComment')->name('comment.like');
});

Route::get('/cdn/{project}-{key}.css', 'CdnController@returnStyle')
  ->where(['project' => '[a-z]+', 'key' => '[0-9a-z]+']);

Route::group(['prefix' => 'banners'], function () {
	Route::post('/close-banner', 'BannersController@closeBanner');
	Route::post('/click-counter', 'BannersController@clickCounter');
});

Route::group(['prefix' => 'adverts'], function () {
	Route::get('/', function () {
		return view('adverts.adverts-categories');
	})->name('adverts.category');
	Route::get('/adverts/{category_slug}/{id}-{article_slug}', 'AdvertsController@showNewsPage')
		->where(['category_slug' => '[a-z-]+', 'id' => '[0-9]+'])
		->name('advert.single');
});

Route::post('contacts', 'PagesController@saveContacts');

Route::group(['prefix' => 'profile'], function () {
	Route::get('/', 'ProfileController@profile')->name('profile');
//	Route::get('/notifications', 'ProfileController@notifications')->name('profile.notifications');
//	Route::get('/profile-edit', 'ProfileController@profileEdit')->name('profile.edit');
//	Route::get('/profile-update', 'ProfileController@profileUpdate')->name('profile.update');
//	Route::get('/change-password-edit', 'ProfileController@changePasswordEdit')->name('profile.change-password-edit');
//	Route::get('/change-password-update', 'ProfileController@changePasswordUpdate')->name('profile.change-password-update');
//	Route::get('/comments', 'ProfileController@comments')->name('profile.comments');
//	Route::get('/adverts', 'ProfileController@adverts')->name('profile.adverts');
//	Route::get('/create-advert', 'ProfileController@createAdvert')->name('profile.create-advert');
//	Route::get('/edit-advert', 'ProfileController@editAdvert')->name('profile.edit-advert');
//	Route::get('/update-advert', 'ProfileController@updateAdvert')->name('profile.update-advert');
//	Route::get('/bookmarks', 'ProfileController@bookmarks')->name('profile.bookmarks');
//	Route::get('/hz-button', 'ProfileController@addNewRecords')->name('profile.');
	Route::get('/organization-changes-list', 'ProfileController@organizationChangesIndex');
	Route::get('/organization-edit/{id}', 'ProfileController@organizationChangesShow');
	Route::post('/organization-save', 'ProfileController@organizationChangesStore');
	Route::patch('/organization-save/{id}', 'ProfileController@organizationChangesUpdate');
	Route::delete('/organization-delete/{id}', 'ProfileController@organizationChangesDestroy');
	Route::get('/organization-list', 'ProfileController@organizationList');
});

//Route::get('test-facebook', 'ApiController@sendLinkToFacebook');

Route::get('sitemap-create', function(){
	Artisan::call('sitemap:create');
	return '{success:created}';
});

//Route::get('twitter-post', function (){
//	Artisan::call('twitter:post');
//});

Route::get('cache-clear', function(){
	Artisan::call('cache:clear');
});

//TODO хай поки буде :)
//Route::get('process-images', function () {
//
//	$organizations = \App\Organization::where('id', '>', 59)->get();
//
//	foreach ($organizations as $organization) {
//		$image = Image::make($organization->getCroppedImage('max'));
//		$image->fit(66, 66);
////		return $image->response('jpg', 95);
//
//		$image->encode('jpg', 95);
//
//		Storage::disk('public')
//			->put('organizations/'.$organization->image.'_brief.jpg', (string)$image);
//	}
//});

//Route::get('/test-imgix', function () {
//	return view('test-imgix');
//});

Route::get('/adverts/single', function () {
	return view('adverts.adverts-single');
});

Route::get('/adverts/form', function () {
	return view('adverts.adverts-form');
});

app/Organization.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

use App\Traits\Crops;
use App\Traits\Relations\OrganizationRelations;
use Carbon\Carbon;
use Illuminate\Database\Eloquent\SoftDeletes;

class Organization extends Model
{
	use OrganizationRelations, SoftDeletes, Crops;

	protected $casts = [
		'schedule' => 'array',
		'break_time' => 'array',
		'addresses' => 'array',
		'emails' => 'array',
		'phones' => 'array',
		'sites' => 'array',
		'social_networks' => 'array',
		'specifics' => 'array'
	];
	protected $table = 'organizations';
	protected $crops_key = 'organizations';
	protected $dates = ['created_at', 'updated_at', 'deleted_at'];
	protected $days = [
		1 => 'Пн',
		2 => 'Вт',
		3 => 'Ср',
		4 => 'Чт',
		5 => 'Пт',
		6 => 'Сб',
		7 => 'Нд',
	];

	public function scopeActive($query)
	{
		return $query->where('active', true);
	}

	public function save(array $options = [])
	{
		$authId = \Auth::id();
		$exists = false;
		
		if (!$this->exists) {
			$exists = true;
			$this->creator_id = $authId;
			$this->meta_title = $this->title." у місті Кам'янець-Подільський - Портал міста KP.CITY";
			$this->meta_description = "Інформація про ".$this->title." міста Кам'янця-Подільського. Адреса та контакти, рейтинги та відгуки користувачів на порталі Кам'янця-Подільського KP.CITY";
			$this->meta_keywords = $this->title.", адреса, рейтинги, відгуки, kp.city";
			$category = OrganizationCategory::where('id', $this->category_id)->first();
			$this->search_text = $category->title . ' ' . $category->parent->title;
		}

		$this->editor_id = $authId;

		parent::save($options);

		\App\Notifications\Telegram::organization($exists, $this);
	}

	public function getUrl()
	{
		if($this->id && $this->category->parent) {
			return url('organizations/'.$this->category->parent->slug .'/'.$this->category->slug.'/'.$this->id.'-'.$this->slug);
		}
		return '';
	}

	public function getDays()
	{
		return $this->days;
	}

	public function scheduleCollect()
	{
		$collect = collect($this->schedule);
		$firstDay = $collect->first();

		if(is_array($firstDay)) {
			$workFrom = $firstDay['work_from'];
			$workTo = $firstDay['work_to'];

			foreach ($collect as $workDay) {
				if($workFrom != $workDay['work_from'] || $workTo != $workDay['work_to']) {
					$workFrom = false;
					break;
				}
			}

			if($workFrom) {
				$collect->first_day = $firstDay['day'];
				$collect->last_day = $collect->last()['day'];
			}
		}

		$array = array_diff_key(format_array($this->getDays()), format_array($collect->groupBy('day')->toArray()));
		$weekends = '';
		$count = 0;
		foreach ($array as $key => $value) {
			$weekends .= $this->getDays()[$key] . ', ';
			$count++;
		}
		$collect->weekends = substr($weekends, 0, -2);
		$collect->count_day = $count;

		return $collect;
	}

	public function getToday()
	{
		if(count($this->scheduleCollect()) > 1) {
			$today = $this->scheduleCollect()->firstWhere('day', $this->numberDay);
			if($today['work_from'] && $today['work_to']) {
				return $today;
			}
			return false;
		}
		return null;
	}

	public function getNumberDayAttribute()
	{
		return Carbon::now()->format('N');
	}

	public function convertToDate($time)
	{
		$todayDate =  Carbon::now()->format('Y-m-d');

		return Carbon::parse($todayDate . ' ' . $time);
	}

	public function isOpen()
	{
		$todayParam = $this->getToday();
		$workFrom = $this->convertToDate($todayParam['work_from']);
		$workTo = $this->convertToDate($todayParam['work_to']);

		if ($workFrom > $workTo) {
			if ($workFrom < now()) {
				$workTo->addDay();
			} else {
				$workFrom->subDay();
			}
		}

		if($todayParam === null) {
			return null;
		}

		$todayDate = Carbon::now();

		if($todayParam && ($todayDate > $workFrom && $todayDate < $workTo)) {
			$breakTime = collect($this->break_time)->first();

			if(is_array($breakTime) && $todayDate > $this->convertToDate($breakTime['break_from'])
				&& $todayDate < $this->convertToDate($breakTime['break_to'])) {
				return 'break';
			}
			return true;

		} else {
			return false;
		}
	}

	public function getOrganizationRating()
	{
		return $this->comments()->where([
			['parent_id', '=', null],
			['active', '=', 1]
		])->avg('rating');
	}
}

app/Http/Controllers/OrganizationsController.php
<?php

namespace App\Http\Controllers;

use App\OrganizationCategory;
use Illuminate\Http\Request;

class OrganizationsController extends Controller
{
	public function showOrganizationCategoriesPage()
	{
		$categories = OrganizationCategory::main()
			->active()
			->with(['children' => function ($query){
				$query->active()->orderBy('order_', 'asc');
			}])
			->withCount('children')
			->get();

		$data = [
			'categories' => $categories,
		];

		return view('organizations.organizations-categories')->with($data);
	}

	public function showOrganizationCategoryPage(Request $request, $categorySlug)
	{
		$category = OrganizationCategory::where('slug', $categorySlug)
			->active()
			->firstOrFail();

		$subcategories = OrganizationCategory::where('parent_id', '=', $category->id)
			->orderBy('order_', 'asc')
			->active()->withCount(['organizations' => function ($query) {
				$query->where('active', 1);
			}])
			->with(['organizations' => function ($query) {
				$query->where('active', 1);
			}])
			->get();

		return view('organizations.organizations-category', compact('category', 'subcategories'));
	}

	public function showOrganizationSubcategoryPage(Request $request, $categorySlug, $subcategorySlug)
	{
		$category = OrganizationCategory::where('slug', $categorySlug)
			->active()
			->firstOrFail();

		$subcategory = $category->children()
			->where('slug', '=', $subcategorySlug)
			->active()
			->firstOrFail();

		$onPage = 6;
		$organizations = $subcategory->organizations()->active()->paginate($onPage);
		$onNextPage = 'Завантажити ще ' . on_next_page($onPage, $organizations);
		$showMore = $organizations->lastPage() !== 1;

		if ($request->ajax()) {
			$returnHTML = view('organizations.organizations-list')->with([
				'category' => $category,
				'subcategory' => $subcategory,
				'organizations' => $organizations,
			])->render();

			return response()->json([
				'html'       => $returnHTML,
				'lastPage'   => $organizations->lastPage(),
				'onNextPage' => $onNextPage,
			]);
		}
		
		return view('organizations.organizations-subcategory', compact('category', 'subcategory', 'organizations', 'showMore', 'onNextPage'));
	}

	public function showOrganizationPage(Request $request, $categorySlug, $subcategorySlug, $organizationId, $organizationSlug)
	{
		$category = OrganizationCategory::where('slug', $categorySlug)
			->active()
			->firstOrFail();

		$subcategory = $category->children()
			->where('slug', '=', $subcategorySlug)
			->active()
			->firstOrFail();

		$organization = $subcategory->organizations()
			->where([
				['slug', '=', $organizationSlug],
				['id', '=', $organizationId]
			])
			->with('comments')->withCount(['comments' => function($query) {
				$query->where('active', 1);
			}])
			->firstOrFail();
		$comments = new \App\Comment;
		$organization = $comments->getComments($organization);

		$rating = $comments->getRating($organization->id, 'App\Organization');
		$ratingComments = $comments->ratingComments($organization->id, 'App\Organization');

		$data = [
			'category' => $category,
			'subcategory' => $subcategory,
			'organization' => $organization,
			'ratingComments' => $ratingComments,
			'rating' => $rating,
			'todayParam' => $organization->getToday(),
			'days' => $organization->getDays(),
			'isOpen' => $organization->isOpen(),
		];

		if($organization->gallery) {
			$onPage = 6;
			$gallery = $organization->gallery->photos()->paginate($onPage);
			$data['gallery'] = $gallery;
			$data['galleryShowMore'] = $gallery->lastPage() !== 1;
			$nextPage = 'Завантажити ще ' . on_next_page($onPage, $gallery);
			$data['galleryOnNextPage'] = $nextPage;

			if ($request->ajax() && $request->param == 'gallery') {
				$html = view('organizations.organization-images-list')->with([
					'gallery' => $gallery,
				])->render();


				return response()->json([
					'html'       => $html,
					'lastPage'   => $gallery->lastPage(),
					'onNextPage' => $nextPage,
				]);
			}
		}

		if($organization->news) {
			$news = $organization->news()->active()->published()->paginate(6);
			$data['news'] = $news;
		}

		if($organization->group) {
			$filiations = \App\Organization::where([
				['id', '!=', $organization->id],
				['group_id', '=', $organization->group->id]
			])->active()->paginate(6);
			$data['filiations'] = $filiations;
		}

		return view('organizations.organizations-single')->with($data);
	}

	public function likeOrganization(Request $request)
	{
		$organization = \App\Organization::where('id', $request->organization_id)->first();

		$like = new \App\Like;
		$organization = $like->putLike($organization);

		return response()->json([
			'active' => $organization->user_like,
			'count_likes' => $organization->count_likes,
		]);
	}

	public function addChanges(Request $request)
	{
		$validator = \Illuminate\Support\Facades\Validator::make($request->all(), [
			'organization_id' => 'required|numeric',
			'message' => 'required',
			'g-recaptcha-response' => 'required',
		]);

		if ($validator->fails()) {
			return response()->json([
				'errors' => $validator->errors()
			]);
		}

		$organizationChange = new \App\OrganizationChange;
		$organizationChange->user_id = auth()->check() ? auth()->user()->id : null;
		$organizationChange->organization_id = $request->organization_id;
		$organizationChange->message = $request->message;
		$organizationChange->active = 0;
		$organizationChange->save();


		return response()->json([
			'alert' => view('includes.float-alert')->with([
				'type' => 'success',
				'class' => '',
				'message' => 'Ваші зміни прийняті і будуть розглянуті'
			])->render()
		]);
	}
}

resources/views/organizations/organization-images-list.blade.php
@foreach($gallery as $image)
    <figure class="gallery__item" itemprop="associatedMedia" itemscope itemtype="http://schema.org/ImageObject">
        <a class="gallery__item-image"
           href="{{ $image->getCroppedImageOrError('max', 'jpg', 'image') }}"
           itemprop="contentUrl"
           data-size="{{ config('crops.galleries.main.types.max.w') }}x{{ config('crops.galleries.main.types.max.h') }}">

            <img src="{{ $image->getCroppedImageOrError('low', 'jpg', 'image') }}"
                 alt="{{ $image->image_title }}">

            <img class="b-lazy"
                 data-src="{{ $image->getCroppedImageOrError('card', 'jpg', 'image') }}"
                 itemprop="thumbnail"
                 alt="{{ $image->image_title }}">
        </a>
    </figure>
@endforeach

resources/views/organizations/organization-rating.blade.php
<div class="organization-single__rating m-full">
	<div class="organization-single__rating-left">
		@if(count($ratingComments))
			<div class="organization-single__rating-avatars">
				@foreach($ratingComments as $comment)
					<div class="organization-single__rating-avatar">
						<img class="b-lazy"
								 data-src="{{ $comment->user->getAvatar(!$comment->anonymous) }}"
								 alt="{{ $comment->anonymous ? 'Анонімний користувач' : ($comment->user->name . ' ' . $comment->user->surname) }}">
					</div>
				@endforeach
				@if(count($ratingComments) > 4)
					<div class="organization-single__rating-avatar">+{{ count($ratingComments) - 4 }}</div>
				@endif
			</div>
			<div class="organization-single__rating-votes">
				{{ count($ratingComments) }} {{ num2word(count($ratingComments), ['оцінка', 'оцінки', 'оцінок']) }}	закладу
			</div>
		@else
			<div class="organization-single__rating-votes">Ще немає оцінок</div>
		@endif
	</div>
	<div class="organization-single__rating-right">
		<span>Оцінка закладу:</span>
		<div class="rating" title="{{ number_format($rating, 1) }}">
			@php $rating = round($rating) @endphp
			@for($i=1; $i<=5; $i++)
				<div class="rating__item @if($i <= $rating) active @endif">
					<i class="fa fa-star"></i>
				</div>
			@endfor
		</div>
	</div>
</div>

resources/views/organizations/organizations-categories.blade.php
@extends('layouts.layouts-main')

@section('meta')

	@include('includes.meta', [
		'title' => config('metatags.organization_categories.title'),
		'meta_description' => config('metatags.organization_categories.description'),
		'meta_keywords' => config('metatags.organization_categories.keywords'),
		'og_title' => config('metatags.organization_categories.title'),
		'og_description' => config('metatags.organization_categories.description'),
		'og_image' => asset('images/pages/homepage.jpg'),
		'active' => true
	])
@stop

@section('styles')
	<link rel="stylesheet" href="{{ mix('css/common.css') }}">
	<link rel="stylesheet" href="{{ mix('css/organizations.css') }}">
	<link rel="stylesheet" href="{{ asset('libs/lightslider/lightslider.css') }}">
@endsection

@section('content')

	<div class="breadcrumbs">
		@include('includes.breadcrumbs', ['current' => 'Заклади міста'])
	</div>

	{{--<div class="slider-section m-full">--}}
		{{--<div class="slider-section__header">--}}
			{{--<h3 class="slider-section__title">Головні спонсори</h3>--}}
			{{--<div class="slider-section__controls">--}}
				{{--<div class="slider-section__controls--prev" id="organizations-slider-prev">--}}
					{{--<i class="fal fa-angle-left"></i>--}}
				{{--</div>--}}
				{{--<div class="slider-section__controls--next" id="organizations-slider-next">--}}
					{{--<i class="fal fa-angle-right"></i>--}}
				{{--</div>--}}
			{{--</div>--}}
		{{--</div>--}}
		{{--<div class="slider-section__content" id="organizations-slider">--}}
			{{--@include('organizations.organizations-list')--}}
		{{--</div>--}}
	{{--</div>--}}

	{{--<hr>--}}

	@include('search.search-block', ['class' => 'm-full'])

	<hr>

	@include('includes.banners.top-banner')

	@if(isset($categories) && count($categories) > 0)
		<div class="oc-list p-t m--b">
			@foreach($categories->sortBy('title') as $category)
				<div class="oc {{ $category->children_count == 0 ? 'without-subcategories' : '' }}"
						 style="background-image: url({{ Storage::url($category->icon) }})">
					<a href="{{ url('/organizations/'.$category->slug) }}" class="oc__content">
						<div class="oc__title">{{ $category->title }}</div>
						<div class="oc__count">Закладів: {{ $category->getOrganizationsCount() }}</div>
					</a>
					@if($category->children_count > 0)
						<a class="oc__btn"><i class="fal fa-angle-down"></i></a>
						<ul class="oc__subcategories">
							@foreach($category->children as $child)
								<li>
									<a href="{{ url('/organizations/'.$category->slug.'/'.$child->slug ) }}">{{ $child->title }}</a>
								</li>
							@endforeach
						</ul>
					@endif
				</div>
			@endforeach
		</div>
	@endif

@stop

@section('scripts')
	<script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@12.0.0/dist/lazyload.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/sticky-sidebar@3.3.1/dist/sticky-sidebar.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/resize-sensor@0.0.6/ResizeSensor.min.js"></script>

	<script src="{{ asset('js/common-slider.js') }}"></script>
	<script src="{{ asset('libs/lightslider/lightslider-blur-fix.min.js') }}"></script>
	<script>
		commonSlider('organizations-slider');
	</script>
@stop

resources/views/organizations/organizations-category.blade.php
@extends('layouts.layouts-main')

@section('meta')
	@include('includes.meta', [
		'title' => $category->meta_title,
		'meta_description' => $category->meta_description,
		'meta_keywords' => $category->meta_keywords,
		'og_title' => $category->og_title ?? $category->meta_title,
		'og_description' => $category->og_description ?? $category->meta_description,
		'og_image' => $category->getCroppedImage('og', 'jpg', 'og_image') ?? asset('images/pages/homepage.jpg'),
		'og_image_type' => 'og',
		'active' => true
	])
@stop

@section('styles')
	<link rel="stylesheet" href="{{ mix('css/common.css') }}">
	<link rel="stylesheet" href="{{ mix('css/organizations.css') }}">
	<link rel="stylesheet" href="{{ asset('libs/lightslider/lightslider.css') }}">
@endsection

@section('content')

	<div class="breadcrumbs">
		@include('includes.breadcrumbs', ['links' => [
			['link' => route('organizations.categories'), 'title' => 'Заклади міста'],
		], 'current' => $category->title])
	</div>

	{{--<div class="slider-section m-full">--}}
		{{--<div class="slider-section__header">--}}
			{{--<h3 class="slider-section__title">Спонсори категорії</h3>--}}
			{{--<div class="slider-section__controls">--}}
				{{--<div class="slider-section__controls--prev" id="organizations-slider-prev">--}}
					{{--<i class="fal fa-angle-left"></i>--}}
				{{--</div>--}}
				{{--<div class="slider-section__controls--next" id="organizations-slider-next">--}}
					{{--<i class="fal fa-angle-right"></i>--}}
				{{--</div>--}}
			{{--</div>--}}
		{{--</div>--}}
		{{--<div class="slider-section__content" id="organizations-slider">--}}
			{{--@include('organizations.organizations-list')--}}
		{{--</div>--}}
	{{--</div>--}}

	{{--<hr>--}}

	@include('search.search-block', ['class' => 'm-full'])

	<hr>

	@include('includes.banners.top-banner')

	@foreach($subcategories as $subcategory)
		@if(!$loop->first)
			<hr class="m-t">
		@endif

		@if($subcategory->organizations_count > 0)
			<div class="slider-section m-full">
				<div class="slider-section__header">
					<h3 class="slider-section__title">
						<a href="{{ route('organizations.subcategory', ['category_slug' => $category->slug, 'subcategory_slug' => $subcategory->slug ]) }}">{{ $subcategory->title }}</a>
					</h3>
					<div class="slider-section__controls">
						<div class="slider-section__controls--prev" id="{{ $subcategory->slug }}-slider-prev">
							<i class="fal fa-angle-left"></i>
						</div>
						<div class="slider-section__controls--next" id="{{ $subcategory->slug }}-slider-next">
							<i class="fal fa-angle-right"></i>
						</div>
					</div>
				</div>
				<div class="slider-section__content" id="{{ $subcategory->slug }}-slider">
					@include('organizations.organizations-list', [
					'organizations' => $subcategory->organizations->take(5),
					'category' => $category,
					'subcategory' => $subcategory
					])
				</div>
			</div>

			<a href="{{ route('organizations.subcategory', ['category_slug' => $category->slug, 'subcategory_slug' => $subcategory->slug ]) }}" class="load-more m-lr">Переглянути всі</a>
		@else
			<h3 class="section-title m-full">
				<a href="{{ route('organizations.subcategory', ['category_slug' => $category->slug, 'subcategory_slug' => $subcategory->slug ]) }}">{{ $subcategory->title }}</a>
			</h3>

			@include('includes.alert', [
				'type' => 'info',
				'class' => 'm-lr',
				'messages' => ['Упс... Закладів не знайдено, але найближчим часом ми це виправимо']
			])
		@endif

	@endforeach

@stop

@section('scripts')
	<script src="https://cdn.jsdelivr.net/npm/vanilla-lazyload@12.0.0/dist/lazyload.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/jquery@3.4.1/dist/jquery.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/sticky-sidebar@3.3.1/dist/sticky-sidebar.min.js"></script>
	<script src="https://cdn.jsdelivr.net/npm/resize-sensor@0.0.6/ResizeSensor.min.js"></script>

	<script src="{{ asset('js/common-slider.js') }}"></script>
	<script src="{{ asset('libs/lightslider/lightslider-blur-fix.min.js') }}"></script>
	<script>
		commonSlider('organizations-slider');
		@foreach($subcategories as $subcategory) commonSlider('{{ $subcategory->slug }}-slider'); @endforeach
	</script>
@stop